/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/comments": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          photo_id?: parameters["rowFilter.comments.photo_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
          is_edited?: parameters["rowFilter.comments.is_edited"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["comments"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          photo_id?: parameters["rowFilter.comments.photo_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
          is_edited?: parameters["rowFilter.comments.is_edited"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          photo_id?: parameters["rowFilter.comments.photo_id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          body?: parameters["rowFilter.comments.body"];
          is_edited?: parameters["rowFilter.comments.is_edited"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
        };
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/likes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          photo_id?: parameters["rowFilter.likes.photo_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["likes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          photo_id?: parameters["rowFilter.likes.photo_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          photo_id?: parameters["rowFilter.likes.photo_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
        };
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/photos": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.photos.id"];
          user_id?: parameters["rowFilter.photos.user_id"];
          title?: parameters["rowFilter.photos.title"];
          url?: parameters["rowFilter.photos.url"];
          is_published?: parameters["rowFilter.photos.is_published"];
          created_at?: parameters["rowFilter.photos.created_at"];
          updated_at?: parameters["rowFilter.photos.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["photos"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** photos */
          photos?: definitions["photos"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.photos.id"];
          user_id?: parameters["rowFilter.photos.user_id"];
          title?: parameters["rowFilter.photos.title"];
          url?: parameters["rowFilter.photos.url"];
          is_published?: parameters["rowFilter.photos.is_published"];
          created_at?: parameters["rowFilter.photos.created_at"];
          updated_at?: parameters["rowFilter.photos.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.photos.id"];
          user_id?: parameters["rowFilter.photos.user_id"];
          title?: parameters["rowFilter.photos.title"];
          url?: parameters["rowFilter.photos.url"];
          is_published?: parameters["rowFilter.photos.is_published"];
          created_at?: parameters["rowFilter.photos.created_at"];
          updated_at?: parameters["rowFilter.photos.updated_at"];
        };
        body: {
          /** photos */
          photos?: definitions["photos"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          nickname?: parameters["rowFilter.users.nickname"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          nickname?: parameters["rowFilter.users.nickname"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          nickname?: parameters["rowFilter.users.nickname"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/handle_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  comments: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `photos.id`.<fk table='photos' column='id'/>
     */
    photo_id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    /** Format: text */
    body: string;
    /** Format: boolean */
    is_edited: boolean;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at: string;
  };
  likes: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `photos.id`.<fk table='photos' column='id'/>
     */
    photo_id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  photos: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    /** Format: text */
    title: string;
    /** Format: text */
    url: string;
    /** Format: boolean */
    is_published: boolean;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at: string;
  };
  users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    full_name: string;
    /** Format: text */
    avatar_url: string;
    /** Format: text */
    nickname?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description comments */
  "body.comments": definitions["comments"];
  /** Format: bigint */
  "rowFilter.comments.id": string;
  /** Format: bigint */
  "rowFilter.comments.photo_id": string;
  /** Format: uuid */
  "rowFilter.comments.user_id": string;
  /** Format: text */
  "rowFilter.comments.body": string;
  /** Format: boolean */
  "rowFilter.comments.is_edited": string;
  /** Format: timestamp with time zone */
  "rowFilter.comments.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.comments.updated_at": string;
  /** @description likes */
  "body.likes": definitions["likes"];
  /** Format: bigint */
  "rowFilter.likes.id": string;
  /** Format: uuid */
  "rowFilter.likes.user_id": string;
  /** Format: bigint */
  "rowFilter.likes.photo_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.likes.created_at": string;
  /** @description photos */
  "body.photos": definitions["photos"];
  /** Format: bigint */
  "rowFilter.photos.id": string;
  /** Format: uuid */
  "rowFilter.photos.user_id": string;
  /** Format: text */
  "rowFilter.photos.title": string;
  /** Format: text */
  "rowFilter.photos.url": string;
  /** Format: boolean */
  "rowFilter.photos.is_published": string;
  /** Format: timestamp with time zone */
  "rowFilter.photos.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.photos.updated_at": string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: text */
  "rowFilter.users.full_name": string;
  /** Format: text */
  "rowFilter.users.avatar_url": string;
  /** Format: text */
  "rowFilter.users.nickname": string;
  /** Format: timestamp without time zone */
  "rowFilter.users.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.users.updated_at": string;
}

export interface operations {}

export interface external {}
